### ISSUE TITLE
Customers are created in Reepay without email/handle

### ISSUE THREAD

**Issue by m-overlund** [RadarsofthouseDev/reepay-payment-for-magento1#1]
Sometimes handle and email is sent to Reepay as null.
This is due to Email isn't always set in Billing Address, if for instance the customer has an account / is logged in.

Fetching it using getCustomerEmail instead should do the trick.
`` $order->getCustomerEmail(); ``

**Comment by RadarsofthouseDev** [comment]
Hi Michael,

Thank you for your suggestion. 

We would like to inform you that we've have tested on standard Magento with onepage checkout. We cannot found the issue and also cannot replicate about this matter as well. From this point, we think that it might be the problem from other plugins or other checkout.

However, we agreed with you to prepare customer email from order data. We also have updated plugin to V.1.0.22 with the customer email changes.
https://github.com/RadarsofthouseDev/reepay-payment-for-magento1/commit/c229ddff6bb76a0fb413f1e2444f16fdaabce56f

Kind regards,
Radarsofthouse
