### ISSUE TITLE
Stalled orders

### ISSUE THREAD

**Issue by MGAndreasen** [RadarsofthouseDev/reepay-payment-for-magento1#4]
If customers leave / don't want to pay anyways, and the dont use the cancle functionality of on the payment page, there current cart is emptied, and a "none valid" unpaied order is placed in the backend.

The main reason for this as I see it, is that the order is made prior to an accepted payment is done sucessfull, instead of just using the quote information for the payment and if its sucessfull, then convert that quote to and order.

Are there anyplans on reworking this extention in one way or another to over come the shortages it has?

**Comment by RadarsofthouseDev** [comment]
Thanks for your report. We apologize for the late reply.
We cannot do anything if user not complete the payment and they just close the payment window.
It is out of control of the module.
And so sorry, we are stopped develop Reepay module for Magento 1.

**Comment by MGAndreasen** [comment]
So the release a few days ago was the last? No more release?

**Comment by RadarsofthouseDev** [comment]
Actually the latest version (1.0.45) was implemented and released on 7 June 2021 (5 months ago) but we forgot to tag the version. 
So, we just tag version a few days ago.
And yes,  No more release for new feature of Reepay MG1 except we have a critical bug :)
