### ISSUE TITLE
Bancontact

### ISSUE THREAD

**Issue by MGAndreasen** [RadarsofthouseDev/reepay-payment-for-magento1#5]
Option to accept

**Comment by RadarSofthouse** [comment]
Request not understood. Please restate.

**Comment by MGAndreasen** [comment]
Feature request to support accepting "Bancontact" payments via this extension.
Reepay have added many new payment options, like p24, Bancontact etc.

**Comment by RadarSofthouse** [comment]
Thanks. P24 is available already - please update your module if you don´t see it. "Bancontact". Waiting for info from Reepay and will add it when confirmed. Thanks for your comment.

**Comment by RadarSofthouse** [comment]
"Bancontact" was added. See code and change log.
