### ISSUE TITLE
iDeal payment is auto settled on reepay, with no authorize part happening

### ISSUE THREAD

**Issue by MGAndreasen** [RadarsofthouseDev/reepay-payment-for-magento1#6]
We are experiencing that iDeal payments is getting directly settled, with no authorized transaction happening as we see it.
This results in us not getting this authorized webhook from reepay, and its leaving our orders payed via iDeal stranded as pending in magento, with no transactions added and no invoice.

Is there a way to include this authorization part for iDeal, or do  we need to have the iDeal payment follow some other flow in the webhooks?  I can see that for some other payment options you have as of lately been adding auto_capture elements, should this also be done for this payment type?

**Comment by RadarSofthouse** [comment]
Hi Michael,

 

Thanks for you email. 

 

Our main developer of the module is back tomorrow morning and will answer your questions. To my knowledge IDeal is not an auto capture payment type so it should follow the standard authorize first flow. Have you enabled webhooks in Reepay for authorize and settle action? 

 



 

 

Please add us to your Reepay account for easier bug fixing: ***@***.*** ***@***.***>  . 

 

 

 

Med venlig hilsen/Best regards 

 

Jesper Brondum

COO

 

Phone:  <tel:+45%2031%2022%2037%2077> +45 3698 1289 (06.00-12.00 CET)

Email:  ***@***.***> ***@***.***

Web:  <http://www.radarsofthouse.dk> www.radarsofthouse.dk

Address: 180/14 Jed Yod Yu Yen Rd, 50300 Chiang Mai, Thailand

LinkedIn:  <https://www.linkedin.com/in/jesper-brondum> dk.linkedin.com/in/jesper-brondum

Skype:  <skype:netdamage?call> Call me on Skype!

 

 

From: Michael Gerner Andreasen ***@***.***> 
Sent: 9. januar 2023 16:00
To: RadarsofthouseDev/reepay-payment-for-magento1 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RadarsofthouseDev/reepay-payment-for-magento1] iDeal payment is auto settled on reepay, with no authorize part happening (Issue #6)

 

We are experiencing that iDeal payments is getting directly settled, with no authorized transaction happening as we see it.
This results in us not getting this authorized webhook from reepay, and its leaving our orders payed via iDeal stranded as pending in magento, with no transactions added and no invoice.

Is there a way to include this authorization part for iDeal, or do we need to have the iDeal payment follow some other flow in the webhooks? I can see that for some other payment options you have as of lately been adding auto_capture elements, should this also be done for this payment type?

**Comment by RadarSofthouse** [comment]
We are looking into this with Reepay.

**Comment by RadarSofthouse** [comment]
@MGAndreasen We just got confirmation from Reepay that it´s a instant capture/seetle payment method so we will change this the flow now and give you an updated module shortly.

**Comment by RadarsofthouseDev** [comment]
@MGAndreasen We just released new version (1.0.52). Please update the module to the latest version.
Thank you :)
