### ISSUE TITLE
Anyday - missing payment info in admin

### ISSUE THREAD

**Issue by m-overlund** [RadarsofthouseDev/reepay-payment-for-magento1#7]
On order view in admin - Payment details does not show when using Anyday
(think there's some issues with Viabill too)

![image](https://user-images.githubusercontent.com/504236/215723860-aebebee7-74da-45fc-bfd6-5c1742840422.png)

**Comment by RadarsofthouseDev** [comment]
@m-overlund Thanks for issue report.
We just released new version (V 1.0.53) Please update the module :)
